[package]
name = "temper"
version = "0.2.0"
authors = ["Felix Obenhuber <felix@obenhuber.de>"]
edition = "2018"

[dependencies]
anyhow = "1.0.28"
hidapi = "1.2.1"
structopt = { version = "0.3.13", default-features = false }
